### PR TITLE
go back to mmap, about 2x faster than any impl before

### PR DESCRIPTION
**Pull request by undefinedDarkness**
I'm done
This is now slightly faster than the multithreaded rust implementation on my machine :D
Edit: might suffer from memory issues with larger files but I really don not care

### CODE REVIEW

**Comment by crumbtoo** [comment]
this is so cool. unironically proud of you, stranger. frothing at the mouth to get a better look at it when i'm homeimage

**Comment by crumbtoo** [comment]
it looks like some counts are off :(
```md
## getshells-c
/bin/bash	57971
/bin/csh	41414
/bin/fish	5557
/bin/ksh	62589
/bin/pdksh	46036
/bin/sh	41780
/bin/zsh	42645
/sbin/bash	45944
/sbin/csh	13671
/sbin/ksh	54173
/sbin/pdksh	49656
/sbin/sh	58501
/usr/bin/bash	41735
/usr/bin/csh	49895
/usr/bin/fish	54071
/usr/bin/ksh	58721
/usr/bin/pdksh	5373
/usr/bin/sh	37910
/usr/bin/zsh	37541

## release/getshells
/bin/bash: 57971
/bin/csh: 41414
/bin/fish: 71093
/bin/ksh: 62589
/bin/pdksh: 46036
/bin/sh: 41780
/bin/zsh: 108181
/sbin/bash: 45944
/sbin/csh: 79207
/sbin/ksh: 54173
/sbin/pdksh: 49656
/sbin/sh: 58501
/usr/bin/bash: 41735
/usr/bin/csh: 49895
/usr/bin/fish: 54071
/usr/bin/ksh: 58721
/usr/bin/pdksh: 70909
/usr/bin/sh: 37910
/usr/bin/zsh: 37541

## getshells-cpp
/bin/bash: 57971
/bin/csh: 41414
/bin/fish: 71093
/bin/ksh: 62589
/bin/pdksh: 46036
/bin/sh: 41780
/bin/zsh: 108181
/sbin/bash: 45944
/sbin/csh: 79207
/sbin/ksh: 54173
/sbin/pdksh: 49656
/sbin/sh: 58501
/usr/bin/bash: 41735
/usr/bin/csh: 49895
/usr/bin/fish: 54071
/usr/bin/ksh: 58721
/usr/bin/pdksh: 70909
/usr/bin/sh: 37910
/usr/bin/zsh: 37541
```

my immediate suspect is line 57:
```c
int id = (colon[shellSize - 3] ^ shellSize + colon[shellSize-4]) & 0xabcdff;
```
because 0xabcdff > 127, and it isn't of form 2^n-1. but i played around with it and it didn't seem to affect it surprisingly... i am running on a single can of redbull i haven't slept in 30 hours so i'm not looking further into this :skull:

**Comment by crumbtoo** [comment]
ermmmm...image

**Comment by einheit** [comment]
rosie-at-the-lake

**Comment by undefinedDarkness** [comment]
Ill run some tests later, could also be the itoa function making a mistable

**Pull request merged**
